name: Publish @cohostvip/runtime-types

on:
  push:
    branches: [main]
    paths:
      - "packages/runtime-types/**"
      - ".github/workflows/publish-runtime-types.yml"

jobs:
  publish:
    name: Lint, Test, and Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/runtime-types

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & PNPM
        uses: ./.github/actions/setup-node-pnpm

      - name: Lint
        run: pnpm -w run lint

      - name: Run tests
        run: pnpm -w run test

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
