name: Publish @cohostvip/runtime-types

on:
  push:
    branches: [main]
    paths:
      - "packages/runtime-types/**"
      - ".github/workflows/publish-runtime-types.yml"

jobs:
  publish:
    if: github.repository == 'cohostvip/cohost-runtime-sdk'
    name: Lint, Test, and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: packages/runtime-types

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & PNPM
        uses: ./.github/actions/setup-node-pnpm

      - name: write token into .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc


      - name: Lint
        run: pnpm -w run lint

      - name: Run tests
        run: pnpm -w run test

      - name: Build
        run: pnpm build

      

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
